---
sudo: required
dist: trusty

language: php

php:
  - 7.0

addons:
  apt:
    sources:
    - sourceline: 'ppa:ansible/ansible'
    packages:
    - ansible

#install:
#  - composer install

script:
- sudo systemctl stop mysql-server || true
- sudo apt-get -y remove --purge mariadb* mysql* || true
- sudo rm -Rf /var/lib/mysql/ || true
- (cd maintenance/demo-install && ansible-playbook -i inventory.local site.yml)
