---
sudo: required
dist: trusty

language: php

php:
  - 7.1

addons:
  apt:
    sources:
    - sourceline: 'ppa:ansible/ansible'
    packages:
    - ansible

#install:
#  - composer install

script:
- (cd maintenance/demo-install && ansible-playbook -i inventory.local site.yml)
