---
# MariaDB install, based partly on https://stackoverflow.com/questions/16444306/ansible-idempotent-mysql-installation-playbook
- name: mariadb server is installed
  apt: package=mariadb-server state=present
  tags: mariadb

- name: python-mariadbdb is installed
  apt: package=python-mysqldb state=present
  tags: mariadb

#- name: mariadb server is enabled
#  service: name=mysql enabled=yes state=started
#  tags: mariadb

- name: mariadb root password is set for all root accounts
  mysql_user: name=root host={{ item }} password={{ mariadb_root_password }} priv=*.*:ALL,GRANT
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost
  tags: mariadb

- name: copy .my.cnf file with root password credentials
  template: src=my.cnf.j2 dest=/root/.my.cnf owner=root mode=0600
  tags: mariadb

- name: delete anonymous mariadb server user for localhost
  action: mysql_user user="" state=absent
  tags: mariadb

- name: remove the mariadb test database
  action: mysql_db db=test state=absent
  tags: mariadb

- name: Create Application Database
  mysql_db: name={{ app_db_name }} state=present
  tags: mariadb

- name: Create Application DB User
  mysql_user: name={{ app_db_user }} password={{ app_db_pass }} priv=*.*:ALL host="localhost" state=present
  tags: mariadb

# TODO ?? Probably not necessary
# mariadb_tzinfo_to_sql /usr/share/zoneinfo | mysql -u root mariadb -p
